general = {
  name = "sMS-1000SQ";
  interpolation = "basic";
  audio_backend_buffer_desired_length_in_seconds = 5.0;
  disable_synchronization = "yes";
  default_airplay_volume = -15.0;
  ignore_volume_control = "no";
  volume_range_db = 60;
};

alsa = {
  output_device = "plughw:0,0";
  use_precision_timing = "no";
  buffer_size = 96000;
  output_rate = 44100;
  output_format = "S16_LE";
};

sessioncontrol = {
  allow_session_interruption = "yes";
  session_timeout = 20;
};

metadata = {
  enabled = "yes";
  include_cover_art = "yes";
  pipe_name = "/tmp/shairport-sync-metadata";
};